stages:
  - build
  - package

build:win:
  stage: build
  before_script:
    - chcp 65001
    - git submodule update --init --recursive
  script:
    - cd nuget
    - git clen -fxd .
    - pwsh BuildWindows.ps1
  tags:
    - windows
    - cuda
  artifacts:
    paths:
      - nuget/artifacts

build:ubuntu:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - cd nuget
    - pwsh BuildUbuntu18.ps1
  tags:
    - ubuntu
    - cuda
  artifacts:
    paths:
      - nuget/artifacts

build:osx:
  stage: build
  before_script:
    - git submodule update --init --recursive
  script:
    - cd nuget
    - pwsh BuildOSX.ps1
  tags:
    - osx
  artifacts:
    paths:
      - nuget/artifacts

package:
  stage: package
  script:
    - cd nuget
    - pwsh CreateAllPackage.ps1
  tags:
    - windows
  dependencies:
    - build:win
    - build:ubuntu
    - build:osx
  artifacts:
    paths:
      - nuget/*.nupkg
